#+TITLE: Computer Animation
# Компјутерска Анимација
#+SUBTITLE: course informationинформации за курсот
#+AUTHOR: Boban Joksimoksi
#+EMAIL: boban.joksimoski@finki.ukim.mk
#+DATE: 2020-02-20
#+OPTIONS: toc:t

* Teachers
- professor: Ivan Chorbev
- teaching assistant: Boban Joksimoski

* Course goals:
- Basics of Computer animationОснови на компјутерска анимација
- Learning and use of a 3D software (Autodesk Maya) for making computer animations

* Prerequisites:
*За упис на предметот без положено компјутерска графика, потребна е молба и потпис од професорот на предметот.*

1. Основи на компјутерска графика/Компјутерска графика

* Course structure
1. Вовед, историја и преглед на областа
2. Генерален вовед во софтверската алатка Autodesk Maya и запознавање на интерфејсот.
3. Моделирање на објекти во Maya преку употреба на полигонална и NURBS геометрија.
4. Анимирање на тела
5. Деформирање и ригување
6. Програмирање и скриптање во Maya
7. Сенчање и осветлување
8. UV координати и текстурурање
9. Камера, рендерирање и композитирање

подетални информации се дадени на следниот [[http://finki.ukim.mk/Content/contentFiles/studies_menustructure/Predmeti/Dodiplomski/finki2.0/Kompjuterska_animacija.pdf][документ]].

* Соработка со индустријата
  Курсот е развиен во соработка со компанијата [[http://www.fx3x.com][FX3X]] и во текот на курсот се врши посета на компанијата. 
* Начин на полагање
- лабораториски вежби - 20% :: лабораториските вежби се оценуваат преку присуствот и активност на студентите
- домашни работи - 20% :: во текот на семестарот ќе бидат зададени 2 домашни работи, секоја од нив носи по 10%
- полагање :: колоквиум или испит - 20%
- завршен проект - 40% :: во координација со наставниците, се одредува завршен проект кој студентот треба да го изработи за да го положи курсот.

